### ISSUE TITLE
AmbiguousModuleResolutionError

### ISSUE THREAD

**Issue by nwabdou85** [oksktank/react-native-pure-chart#1]
Hi

my app when using react native pure chart with react native, saying that react_native_information.js tries to require accessibilityinfo.js but there is several fils providing this modules, asking to fix it or delet it; and giving a full url of it (accessibilityinfo.android.js) in react native chart part folder;
I delete it but the error remains.

How can I fix it , please ?

**Comment by oksktank** [comment]
Hi

Thank you for using react native pure chart.
I've noticed that our project's dependency list contains 'react-native'
I removed it and published 0.0.12 to npm repository

Could you update to a new version of react-native-pure-chart(0.0.12) and try it again? 

Please comment here when you still have a problem with using react-native-pure-chart.

**Comment by nwabdou85** [comment]
@oksktank  the problem is resolved, but another one is apppeard

get a llok at this picture, please
![26056680_1461404317248870_572419106_n](https://user-images.githubusercontent.com/6404998/34340094-d117d9b0-e97d-11e7-9f76-a9bf2e03cf8b.png)

**Comment by nwabdou85** [comment]
@oksktank  any solution to the problem?

**Comment by kingwang09** [comment]
@nwabdou85 
Hi

Thank you for using react native pure chart.
and sorry for late reply.

Is there a blank in the data?

**Comment by nwabdou85** [comment]
@oksktank  There are always a conflict with react native using version 0.0.10

**Comment by kingwang09** [comment]
@nwabdou85 

We have developed the multi series function.
We will do more testing and release release 0.0.12 until today.

sorry & thanks.

**Comment by nwabdou85** [comment]
@oksktank  Thank's, I'm waiting for the release today :)

**Comment by oksktank** [comment]
@nwabdou85 

We have released 0.0.13 now.
It contains multi series chart and bug fixed
Thank you for you feedback.

**Comment by nwabdou85** [comment]
@oksktank @kingwang09  I'm trying it right now and give you me feedback after :)
