### ISSUE TITLE
How can I custom point on the line chart and write value on it?

### ISSUE THREAD

**Issue by amy1602** [oksktank/react-native-pure-chart#10]

**Comment by oksktank** [comment]
Hi, amy1602

could you describe your issue more detail? I'm not sure i understood your question.
Is that mean you want your line chart look's like below image?
https://geekalicious.pt/phpopenchart/assets/images/examples/line-basic.png

or add custom values in x-axis or y axis?

**Comment by amy1602** [comment]
Yes. I want my line chart look's like that image.

**Comment by oksktank** [comment]
Oh i see.

Sadly that function not available in current version.
I'll add this feature soon.
Thank you for your feedback.

**Comment by oksktank** [comment]
Hi amy1602,

Sorry for late.
I've just released v0.0.20 to npm repository and now you can add custom value on line chart.

You can add your custom renderer for custom value like below code.
`<PureChart type={'line'}
            data={this.state.data}
            width={'100%'}
            height={200}
            customValueRenderer={(index, point) => {
              return (
                <Text style={{textAlign: 'center'}}>{point.y}</Text>
              )
            }}/>`

Thank you
