### ISSUE TITLE
No way to turn off the animation

### ISSUE THREAD

**Issue by damianvisser** [oksktank/react-native-pure-chart#106]
The animation is called whenever the state re renders. This is very annoying when trying to change your state.I can't seem to find a way to turn the animation off.

**Comment by crkacer** [comment]
Same here, looking for solution.

**Comment by marciliocb** [comment]
@Vissnor @crkacer please checkout my PR that address this issue. Hope it helps :)
Best!

**Comment by crkacer** [comment]
Cool! That's what I'm looking for. Highly appreciate!

**Comment by AlexeyShevchenko27** [comment]
> @Vissnor @crkacer please checkout my PR that address this issue. Hope it helps :)
> Best!

Is this for pie charts only?

**Comment by marciliocb** [comment]
Just updated the fix-animated branch with the implementation for all types
of chart.
