### ISSUE TITLE
Single data Point Bug

### ISSUE THREAD

**Issue by pedrohbtp** [oksktank/react-native-pure-chart#11]
First, great work on the components!

Passing a single data point does not render properly.
<PureChart type={'line'} data={
                                    [{ x: '2018-01-01', y: 30 }]
                                } />

![image](https://user-images.githubusercontent.com/3597229/37303938-d8d47848-260e-11e8-9e99-9d68895a7d6b.png)

and when I tap on the graph, it crashes:

![image](https://user-images.githubusercontent.com/3597229/37304078-53da70a6-260f-11e8-8823-736e8b669940.png)

Passing multiple points works fine
<PureChart type={'line'} data={
                                    [{ x: '2018-01-01', y: 30 }, { x: '2018-01-01', y: 30 }]
                                } />

![image](https://user-images.githubusercontent.com/3597229/37304007-154228f2-260f-11e8-8802-d24eb58eb8aa.png)

**Comment by pedrohbtp** [comment]
Any ideas about it?
Thanks

**Comment by oksktank** [comment]
This bug will be fixed in the next release.(may be released in 3/22)
I forgot testing with unordinary inputs. thank you for reporting!

**Comment by oksktank** [comment]
I released new version of react-native-pure-chart just now(0.0.19) and single point bug fixed.
