### ISSUE TITLE
 prop type `height` is invalid

### ISSUE THREAD

**Issue by fgvicente** [oksktank/react-native-pure-chart#12]
Warning: Failed prop type: PureChart: prop type `height` is invalid; it must be a function, usually from the `prop-types` package, but received `number`.
- node_modules/fbjs/lib/warning.js:33:20 in printWarning
- node_modules/fbjs/lib/warning.js:57:25 in warning
- node_modules/prop-types/checkPropTypes.js:52:18 in checkPropTypes
- node_modules/react/cjs/react.development.js:1171:19 in validatePropTypes
- node_modules/react/cjs/react.development.js:1268:22 in createElementWithValidation
* pages/Living.js:16:24 in render
- node_modules/react-proxy/modules/createPrototypeProxy.js:44:35 in proxiedMethod
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:7866:21 in finishClassComponent
- ... 18 more stack frames from framework internals

**Comment by isthaison** [comment]
PureChart.propTypes = {
  type: PropTypes.string.isRequired,
  data: PropTypes.array.isRequired,
  color: PropTypes.string,
 -- height: PropTypes.number,
}
PureChart.defaultProps = {
  color: '#297AB1',
  --height:100
}

**Comment by oksktank** [comment]
Oh it was my mistake.

I fixed it and released 0.0.18.
Thank you for reporting.

**Comment by isthaison** [comment]
when is you release chart pie ?

**Comment by oksktank** [comment]
@isthaison we tried hard to implement pie chart, but we got some trouble in android because it doesn't support skew transform. we found another way to implement pie chart both android and ios.
It will be released within three weeks. 

Thank you
