### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by ceessay** [oksktank/react-native-pure-chart#126]
Hi. We are looking for a react-native charting library without overhead, this one seems interesting.
Just Wanted to know of this one is still maintained. 
Last commit has been made 2 years ago an 11 pull requests are waiting.

**Comment by oksktank** [comment]
Hi. For a variety of reasons we are not maintaining for a long time. Currently, there are no patch plans, but later this year we are planning a new version that supports react 17 and typescript. Until then, react-native-pure-chart is not recommended to use it in production.

**Comment by ceessay** [comment]
Ok. Looking forward to that new version. Thanks !
