### ISSUE TITLE
Support Pie chart?

### ISSUE THREAD

**Issue by jose920405** [oksktank/react-native-pure-chart#14]

**Comment by oksktank** [comment]
Not now. but it will be released soon. we're trying hard to implement pie chart, and almost done.
![2018-03-22 10 36 30](https://user-images.githubusercontent.com/2025036/38451510-124a35a6-3a6c-11e8-929a-be8f5b7324cf.png)

thank you

**Comment by jejesh26** [comment]
looking forward to get pie chart and if possible next, heatmap :-)

**Comment by oksktank** [comment]
@jose920405 @sonnguyenit @jejesh26 
we added pie chart in 0.0.22.

please try this new feature and if you have a question about this, feel free to contact us.

Thank you and sorry for late.

**Comment by oksktank** [comment]
There were fail at publish to npm repository. I'll publish new version as soon as possible.

**Comment by oksktank** [comment]
Now you can use pie chart with updating to 0.0.22
