### ISSUE TITLE
How can i add min value to line chart ?

### ISSUE THREAD

**Issue by vengal** [oksktank/react-native-pure-chart#15]
Currently line chart y axis starts from 0 to max value. Is it possible to replace 0 with some other value so that y axis line will be between custom min value to max value ?

**Comment by narnia1991** [comment]
+1

**Comment by vengal** [comment]
@oksktank 
Hi , thanks for quick reply. 
May i know when i can expect this feature ? I need it badly. Based on timeline i have to decide usage of this library ?

**Comment by oksktank** [comment]
@vengal 
Hi again. I tried to implement supporting minimum value property and it's almost done.
Sadly, it will be released within next monday not today.(because of some bugs)

**Comment by oksktank** [comment]
@vengal, @narnia1991 

Hi, sorry for late update.

It is possible in v0.0.21.
You can use 'minValue' props to <PureChart>

example) <PureChart minValue={20} ... />
