### ISSUE TITLE
Add ability to set the background color for charts

### ISSUE THREAD

**Issue by fkhosrow** [oksktank/react-native-pure-chart#17]
How can I change the background color for the line chart? Thanks.

**Comment by fkhosrow** [comment]
After looking through the implementation code (line-chart.js), The easy fix was to remove the styles.wrapper.backgroundColor property. The backgroundColor can then be set on the parent element in order to set the backgroundColor. Of course, it would be nice to add this as an enhancement.

**Comment by oksktank** [comment]
Thank you for your opinion. 
I'll add background color property to the next release.

**Comment by fkhosrow** [comment]
I checked the latest release and background color was added.
