### ISSUE TITLE
Width 100%??

### ISSUE THREAD

**Issue by tofijak** [oksktank/react-native-pure-chart#19]
I am trying to set the width of the chart to 100%, but nothing is happening. Is it possible to do with your charts?

My Code:
`<View>`
`<PureChart data={sampleData} type='line' width='100%'/>`
`</View>`

**Comment by oksktank** [comment]
PureChart inherits parents width.

Try:

<View style={{width: '100%'}}>
<PureChart data={sampleData} type='line'/>
</View>

**Comment by violabg** [comment]
still not be able to have charts at 100% width on a view

**Comment by shierro** [comment]
Hi @oksktank , are there any work arounds that you can suggest here? thanks

**Comment by erdemkosk** [comment]
same here

**Comment by BillZalokostas** [comment]
Did u guys find a solution?

**Comment by jay70077** [comment]
use defaultColumnWidth instead of width 
defaultColumnWidth:{500}  
@tofijak @violabg @shierro @erdemkosk @oksktank
