### ISSUE TITLE
undefined is not an object in colum-chart-item.js 47

### ISSUE THREAD

**Issue by nwabdou85** [oksktank/react-native-pure-chart#2]
Hi, 

I've just tried it but still does not work; this image of error may help to figure out what was the error

![pure](https://user-images.githubusercontent.com/6404998/34460577-de9dcad8-ee12-11e7-89ca-64d3caa03b11.png)

Thank's

**Comment by oksktank** [comment]
@nwabdou85 

Can you tell me what was a 'data' prop of <PureChart>?

**Comment by oksktank** [comment]
@nwabdou85

could you try add 'prop-types' on your packge.json?

I'll keep trying to find what was a problem but i think this action could be help temporarily.

**Comment by kingwang09** [comment]
@nwabdou85 

and could i know your raw data?

**Comment by nwabdou85** [comment]
@oksktank  @kingwang09  I installed  'prop-types' but the same error; 

the data is the same data in your example   <PureChart data={[30,200,170,250,10]} type='line' />

I use it juste for test it 
![error](https://user-images.githubusercontent.com/6404998/34582030-d65c05d2-f192-11e7-908f-378e170a3a52.png)

**Comment by nwabdou85** [comment]
I write an new app with expo and CRNA to test it, but the same error ;(

**Comment by oksktank** [comment]
@nwabdou85 

Sorry for late reply.

I found i used PropTypes wrong in column-chart-item.js
I replaced PropTypes to using 'prop-types' and i think now you can use react-pure-chart.
Please update react-pure-chart to 0.0.14

Thank you for your kind feedback about our project.

**Comment by nwabdou85** [comment]
for now it's ok. but there is an another issue; I close this and open another
