### ISSUE TITLE
How to draw the chart without grid lines, set the axis and label colors and...

### ISSUE THREAD

**Issue by fkhosrow** [oksktank/react-native-pure-chart#22]
Hi,

1. Is it possible to draw the chart without the grid lines? If the option is not available via the API, can you point me to where I can modify the source code to accomplish this?

2. Is it possible to set the X and Y axis and label colors? If the options is not available via the API, can you point me to where I can modify the source code to accomplish this?

3. Is it possible to draw real-time data with this chart? Basically, I would like to "append" data as it comes in to the chart.

Thanks for all your help and all your hard work for this library.

**Comment by oksktank** [comment]
Hi, @fkhosrow 

I just updated v0.0.21  and it contains below props.
xAxisColor={'#e0e0e0'}
yAxisColor={'#e0e0e0'}
xAxisGridLineColor={'#e0e0e0'}
yAxisGridLineColor={'#e0e0e0'}
labelColor={'#000000'}

You can make transparent grid line with '#FFFFFF00' or 'transparent'

I can't understand your third question, react-native-pure-chart changed when data props changed and i think it can be a real time chart but it always animate again.

Is it right that you want previous values not to be re-animate?

Thank you for your nice feedback

**Comment by fkhosrow** [comment]
Hi @oksktank thank you very much for adding these features. I tried the latest release and the options works great. You were correct w.r.t real time chart as it does draw the new point (in addition to existing points) when I append new data to the prop data. However, I noticed the entire chart points shift up and down as a new point is drawn on the chart. Any ideas?
