### ISSUE TITLE
Skip the value for x-axis point in line chart. 

### ISSUE THREAD

**Issue by vengal** [oksktank/react-native-pure-chart#24]
Is there a way to skip the value for x-axis point ? For example , i want to pass 7 x-axis points , but i have data for 5 points only. So that can we skip drawing line chart for those 2 points.
In the given image as there is no data for 10th and 12th April it just connects to next line. Is it possible to draw like this ?
![line chart](https://user-images.githubusercontent.com/3850171/39904608-5028c65e-54f6-11e8-94c8-a6e43ac920f9.png)

**Comment by octohedron** [comment]
That's simple to fix, before rendering the graph, remove those values from the array, the ones you don't want to render.

For example, using lodash, remove the values in which the y value is 0

```javascript
    _.remove(data, i => {
      return i.y == 0;
    });
```

**Comment by vengal** [comment]
If i remove values where y is 0, that x axis value will not display in x-axis bar. I want that to display in x-axis line.

**Comment by vengal** [comment]
@yogeshR5 No idea. That's only my concern. If you already figured it out, please share the solution with me.

**Comment by vengal** [comment]
@octohedron If i remove values where y is 0, that corresponding x axis value will not display in x-axis bar. I want that to display label in x-axis line. Can you please share the solution with me ?

**Comment by yogeshR5** [comment]
oops!! i didn't use pure chart @vengal

**Comment by vengal** [comment]
@yogeshR5 its require react-native-svg also ? Is it depedent on svg library ?

**Comment by yogeshR5** [comment]
yes... refer https://formidable.com/open-source/victory/docs/native/

**Comment by vengal** [comment]
@oksktank  Hi is it possible to do the below image kind of line chart using pure charts ? I got stuck in this in particular. Purechart is able to do fulfill all my requirements except this ? 
https://user-images.githubusercontent.com/3850171/39904608-5028c65e-54f6-11e8-94c8-a6e43ac920f9.png

**Comment by oksktank** [comment]
@vengal
Hi, it is not possible in pure chart now. I'll do my best to be possible in next release. (May be a Mid-july)

**Comment by vengal** [comment]
@oksktank  Thanks. My project deadline at same time. Please assure me that you can add this feature by Mid July. I will wait for you and implement in my app.
And minValue for line-chart is not working.

**Comment by oksktank** [comment]
@vengal 
Hi, I just updated v0.0.23 to npm repository.
You can use blank value like this:

data =[{x: '2018-07-12', y: 30}, {x: '2018-07-13', y: null}, {x: '2018-07-14', y: 60}]

use null value for y where you want to hide point.

Could you show how you implement? It works well when I use minValue props for PureChart.

**Comment by vengal** [comment]
@oksktank Hi, i am getting crash for above criteria. I am sending null for empty data.

**Comment by vengal** [comment]
@oksktank Ok, thanks.

**Comment by vengal** [comment]
@oksktank May i know progress on this issue ?

**Comment by oksktank** [comment]
@vengal
Sorry for late. I'll do my best to be released within today.

**Comment by vengal** [comment]
@oksktank Thanks in advance ...

**Comment by oksktank** [comment]
@vengal
It is little bit delayed because I`m on a business trip. Sorry for that :(
Now i do some tests for this issue and it will be released within 2 days.

**Comment by vengal** [comment]
@oksktank 
Any update on this ? Have to release my project.

**Comment by oksktank** [comment]
@vengal 
I've updated 0.0.24 to npm repository.
It will be work fine when more than 2 null values.
Sorry for late and check new version please.
