### ISSUE TITLE
there is a problem with scroll

### ISSUE THREAD

**Issue by nwabdou85** [oksktank/react-native-pure-chart#3]
Hi, 

After the last updating to 0.0.14, all works well if you can resolve this problem of scrolling, thank's

Ps: I use it with CRNA and expo projet, so you can test it with to figure out the problem.

![purecharteissue](https://user-images.githubusercontent.com/6404998/34811677-4709d82c-f6a2-11e7-9470-50bc982e0e1a.png)

**Comment by oksktank** [comment]
@nwabdou85 

Could you check below closed issue at react-native repository?
https://github.com/facebook/react-native/issues/16522

It says it is fixed at react-native 0.50.4
