### ISSUE TITLE
[Pie] missing props size

### ISSUE THREAD

**Issue by isthaison** [oksktank/react-native-pure-chart#36]

**Comment by zxcv551133** [comment]
Thank you for using react native pure chart!
Would you explain more specifically?

**Comment by isthaison** [comment]
in file index folder pure chart    
component pie chart
size={this.props.height}
...

**Comment by oksktank** [comment]
Sorry for late, it is fixed in recent version. You can use it like below:

<PureChart typ='pie' size={50} ....
