### ISSUE TITLE
How can I display more points on the y-axis. Seems to default to 3?

### ISSUE THREAD

**Issue by EmirGluhbegovic** [oksktank/react-native-pure-chart#6]

**Comment by oksktank** [comment]
Hi, EmirGluhbegovic.

Sorry for late reply.

Displaying y-axis numbers depends on the max y value.
For example, when max value is 50, it displays [0, 10, 20, 30, 40, 50]
when max value is 2, it display [0.5, 1.0, 1.5, 2.0]

It can not be customized now, but you can change the y-axis numbers(we called 'guide line') with fixing **const getGuideArray** = (max, height) => { ... } in pure-chart/common.js

**Comment by oksktank** [comment]
I released new version(0.0.19) of react-native-pure-chart and you can customize your y-axis guide line count.

You can use like this after update react-native-pure-chart to 0.0.19
<PureChart numberOfYAxisGuideLine={10} ..... /> 

Thank you for your feedback.
