### ISSUE TITLE
axis spacing

### ISSUE THREAD

**Issue by alexcittadini** [oksktank/react-native-pure-chart#7]
Love the library! Is there an easy way to customise the chart or is it all set (ie i need to reduce the spacing between data points)

**Comment by alexcittadini** [comment]
gap={10} does it

**Comment by oksktank** [comment]
Thank you for using react-native-pure-chart.

We're planning to  add gap property to <PureChart> component at next release.
Thank you for your feedback!

**Comment by octohedron** [comment]
@oksktank Would be great to have this on the `README`, had to look for it on the issues.
