### ISSUE TITLE
how to render chart with latest data at the end displayed first?

### ISSUE THREAD

**Issue by rubek-joshi** [oksktank/react-native-pure-chart#77]
What I want is for the chart to display end points at first and then let the user scroll to the left to view previous data.

**Comment by trungnguyencmu** [comment]
+1

**Comment by DanielRicoPensemos** [comment]
> What I want is for the chart to display end points at first and then let the user scroll to the left to view previous data.

Did you find any solution?

**Comment by rubek-joshi** [comment]
> Did you find any solution?

I ended up reversing the data from my backend server.
