### ISSUE TITLE
How i can set height for chart ?

### ISSUE THREAD

**Issue by bboy114crew** [oksktank/react-native-pure-chart#9]

**Comment by zxcv551133** [comment]
Sorry for the late reply.
you can set height by 'props.height'.
<PureChart type={'YOUR TYPE'} data={YOUR DATA} height={YOURHEIGHT} />

**Comment by zxcv551133** [comment]
We have found the opt doesen't work in this version. 
We will fix the problem on next version.

**Comment by oksktank** [comment]
We've released v0.0.17
and it contains [height] props in PureChart
ex) <PureChart .... height={200} />
You can use this props by downloading 0.0.17 at npm repository.

Thank you.

**Comment by reactdevrocks** [comment]
not working height and width both.
